# Configuration file for weather.py
#
# You can obtain the NOAA Office and Station ID by visiting https://www.weather.gov
# and searching for your city and state. Once you get to that page, hover your
# mouse over the link below "You local forecast office is", look for 
# the letters after the last slash in the link.
# The station_id will be in parentheses following "Current conditions at..."


# This is where you want the log file to go, the user running the script MUST
# have write permissions on this file
[log]
file = "/var/log/weather.log"

# You can add as many stations as you would like. Each station takes the form of:
# [[stations]]
# name = "{Station Name}" # This is what appears in the prompt as an option
# noaa_office = "{AAA}"   # See above about obtaining this info
# locale = "{City, ST}"   # This can be whatever you want
# station_id = "{ABCD}"   # See above about obtaining this info
# default = "{True or False}" # Whether or now

[[stations]]
name = "Bullhead"
noaa_office = "VEF"
locale = "Bullhead City, AZ"
station_id = "KIFP"
default = "False"

[[stations]]
name = "Kingman"
noaa_office = "VEF"
locale = "Kingman, AZ"
station_id = "KIGM"
default = "True"

[[stations]]
name = "Havasu"
noaa_office = "VEF"
locale = "Lake Havasu City, AZ"
station_id = "KHII"
default = "False"

[[stations]]
name = "Prescott"
noaa_office = "FGZ"
locale = "Prescott, AZ"
station_id = "KPRC"
default = "False"

[[stations]]
name = "Payson"
noaa_office = "FGZ"
locale = "Payson, AZ"
station_id = "KPAN"
default = "False"

